# Generated by Django 4.2.7 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.CharField(max_length=15)),
                ('addressOne', models.CharField(max_length=150)),
                ('addressTwo', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=11)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
